<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\LucidMicro.BuildingBlocks.Inbox.Abstractions\LucidMicro.BuildingBlocks.Inbox.Abstractions.csproj" />
    <ProjectReference Include="..\LucidMicro.BuildingBlocks.Inbox.Core\LucidMicro.BuildingBlocks.Inbox.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
</Project>
