<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\Core\Application\LucidMicro.BuildingBlocks.Application\LucidMicro.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\..\Core\Domain\LucidMicro.BuildingBlocks.Domain.Core\LucidMicro.BuildingBlocks.Domain.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
